service:
  name: benaton-alexa-skill

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  environment:
    TZ: Asia/Tokyo
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

functions:
  alexa:
    handler: dist/index.handler
    events:
      - alexaSkill
